#include "interface.h"
#include "Model/src/Socket/Client.h"
#include <QApplication>
#include <thread>

using namespace std;
/**
 * @author Jose Espinoza
 * @param argc int parameters for interface integration
 * @param argv char parameter for interface integration
 * @return exception
 */
 /*Auto Generated by QTCreator */
int RunInterface(int argc, char *argv[])
{
    QApplication a(argc, argv);
    interface w;
    w.show();
    return a.exec();
}
/**
 * Calls the singleton instance of the client to start the listening on the socket
 */
void RunClient(){
    Client::getInstance()->initClient();
}
/**
 * @brief Starts two threads, one for the user interface and other for the client loop
 * @param argc int parameters for interface integration
 * @param argv char parameter for interface integration
 * @return exit code
 */
int main (int argc, char *argv[]){
    thread Client (RunClient);
    thread Interface (RunInterface, argc, argv);

    Client.join();
    Interface.join();
}
